# Authors
First Student:$\newline$
    Name: Michelangelo Battista $\newline$
    matriculation number: 6736695 $\newline$
Second Student: $\newline$
    Name: Fabian Lebert $\newline$
    matriculation number: 6648204 $\newline$

# Imports

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris=datasets.load_iris()

# Exercise 1. K-Means Clustering

1)

In [52]:
def kmeans(data=None, ncluster=3):
    #centroids = np.random.randint(150, size=(ncluster,1))
    centroids = np.array([[85],[105],[8]])
    cluster_data = iris.data-iris.data[centroids]
    #test_data = np.sqrt(np.sum((iris.data-iris.data[centroids])**2, axis=1))
    test_data = np.sqrt(np.sum((cluster_data)**2, axis=2))
    #print(iris.data[centroids])
    #test2=test_data.reshape(3,1,150)
    test2=np.amin(test_data,axis=0)
    test_min=np.argmin(test_data,axis=0) # index of minima
    #test2=np.amin(test2,axis=0) # array of minima
    ind_dat=np.column_stack([np.array(test_min),np.array(test2)])
    #print(np.mean(ind_dat[2,True], axis=1))
    test3=np.where(ind_dat[0:]==2)
    print(ind_dat[test3, True])
    #print(test_data)
    #print(test_min)
    #print(test2)
    #print(test_min)
    #print(ind_dat)
    #print(test_data)

kmeans()

[[[2.         0.92195445]
  [2.         0.50990195]
  [2.         0.43588989]
  [2.         0.3       ]
  [2.         0.92195445]
  [2.         1.45945195]
  [2.         0.54772256]
  [2.         0.78740079]
  [2.         0.        ]
  [2.         0.55677644]
  [2.         1.28452326]
  [2.         0.67082039]
  [2.         0.42426407]
  [2.         0.34641016]
  [2.         1.79164729]
  [2.         1.99749844]
  [2.         1.43178211]
  [2.         0.92736185]
  [2.         1.61245155]
  [2.         1.14891253]
  [2.         1.15758369]
  [2.         1.08627805]
  [2.         0.83066239]
  [2.         0.91104336]
  [2.         0.81240384]
  [2.         0.64031242]
  [2.         0.83066239]
  [2.         1.00498756]
  [2.         0.94339811]
  [2.         0.46904158]
  [2.         0.48989795]
  [2.         1.14017543]
  [2.         1.44913767]
  [2.         1.70293864]
  [2.         0.54772256]
  [2.         0.7       ]
  [2.         1.25698051]
  [2.         0.8660254 ]
  [2.       

2)

# Exercise 2. Hierarchical Clustering

In [78]:
#print(iris.data[np.argwhere(iris.data[: ,0] == 5.1)])
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.