# Authors
First Student:$\newline$
    Name: Michelangelo Battista $\newline$
    matriculation number: 6736695 $\newline$
Second Student: $\newline$
    Name: Fabian Lebert $\newline$
    matriculation number: 6648204 $\newline$

# Imports

In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris=datasets.load_iris()

# Exercise 1. K-Means Clustering

1)

In [90]:
def kmeans(data=None, ncluster=3):
    #centroids = np.random.randint(150, size=(ncluster,1))
    centroids = np.array([[85],[105],[8]])
    cluster_data = iris.data-iris.data[centroids]
    #test_data = np.sqrt(np.sum((iris.data-iris.data[centroids])**2, axis=1))
    test_data = np.sqrt(np.sum((cluster_data)**2, axis=2))
    #print(iris.data[centroids])
    print(test_data)

kmeans()

[[3.51994318 3.59722115 3.73229152 3.60693776 3.55105618 3.14483704
  3.64142829 3.45832329 3.79209705 3.54259792 3.37786915 3.43656806
  3.66878727 4.10609303 3.64005494 3.39558537 3.50570963 3.48137904
  3.12729915 3.41467422 3.18747549 3.36749165 4.02616443 3.14165561
  3.18747549 3.39558537 3.29393382 3.40734501 3.49428104 3.47850543
  3.44963766 3.28633535 3.51852242 3.52987252 3.50142828 3.72692903
  3.52987252 3.6207734  3.86264158 3.43074336 3.59722115 3.92300905
  3.84707681 3.22800248 3.02820079 3.591657   3.36749165 3.68374809
  3.39705755 3.54682957 1.05830052 0.45825757 1.03440804 1.34164079
  0.79372539 0.73484692 0.37416574 2.00249844 0.84261498 1.23693169
  2.07846097 0.51961524 1.43178211 0.58309519 1.14455231 0.79372539
  0.57445626 1.02469508 1.22065556 1.25698051 0.42426407 0.84261498
  1.03440804 0.75498344 0.73484692 0.75498344 1.06301458 0.9539392
  0.50990195 1.44568323 1.4106736  1.5        1.02469508 0.92195445
  0.72801099 0.         0.79372539 1.18321596 0.7

2)

# Exercise 2. Hierarchical Clustering

In [78]:
#print(iris.data[np.argwhere(iris.data[: ,0] == 5.1)])
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.